# Generated by Django 3.2.8 on 2023-01-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0002_tb_articulo_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Mascota',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField()),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
    ]
